import pyautogui
from time import sleep
import funcoes
sleep(1)
# pyautogui.keyDown('left') # Precionar  a tecla
while True:
    pyautogui.press('left')
    sleep(0.3)
    pyautogui.press('left')
    sleep(0.3)
    pyautogui.press('left')
    sleep(0.3)
    pyautogui.press('left')
    sleep(0.3)
    pyautogui.press('left')
    sleep(0.3)
    pyautogui.press('left')
    sleep(0.3)

    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)
    pyautogui.press('up')
    sleep(0.3)

    pyautogui.press('right')
    sleep(0.3)
    pyautogui.press('right')
    sleep(0.3)
    pyautogui.press('right')
    sleep(0.3)
    pyautogui.press('right')
    sleep(0.3)
    pyautogui.press('right')
    sleep(0.3)
    pyautogui.press('right')
    sleep(0.3)

    pyautogui.press('Down')
    sleep(0.3)
    pyautogui.press('Down')
    sleep(0.3)
    pyautogui.press('Down')
    sleep(0.3)
    pyautogui.press('Down')
    sleep(0.3)
    pyautogui.press('Down')
    sleep(0.3)
    pyautogui.press('Down')
    sleep(0.3)
    pyautogui.press('Down')
    sleep(0.3)
    pyautogui.press('Down')
    sleep(0.3)
    pyautogui.press('Down')
    sleep(0.3)
